#!/bin/bash

DOCKER_NAME="${DOCKER_NAME:=mb}"
DOCKER_TAG="${DOCKER_TAG:=dev}"
DOCKER_CONTAINER_NAME="${DOCKER_CONTAINER_NAME:=mellanabot}"
DOCKER_REPO="${DOCKER_REPO:=danonthemoon21/mellana-bot}"

PHANTOMBOT_APIOAUTH="${PHANTOMBOT_APIOAUTH:=\"\"}"
PHANTOMBOT_CHANNEL="${PHANTOMBOT_CHANNEL:=mellanatest}"
PHANTOMBOT_OAUTH="${PHANTOMBOT_OAUTH:=\"\"}"
PHANTOMBOT_OWNER="${PHANTOMBOT_OWNER:=danonthemoon}"
PHANTOMBOT_PANELPASSWORD="${PHANTOMBOT_PANELPASSWORD:=admin}"
PHANTOMBOT_PANELUSER="${PHANTOMBOT_PANELUSER:=admin}"
PHANTOMBOT_USER="${PHANTOMBOT_USER:=mellanabot}"

case "$1" in
  build)
    docker build -t "$DOCKER_NAME:$DOCKER_TAG" $(git rev-parse --show-toplevel) 
    ;;
  run)
    docker run \
      -e "PHANTOMBOT_APIOAUTH=$PHANTOMBOT_APIOAUTH" \
      -e "PHANTOMBOT_CHANNEL=$PHANTOMBOT_CHANNEL" \
      -e "PHANTOMBOT_OAUTH=$PHANTOMBOT_OAUTH" \
      -e "PHANTOMBOT_OWNER=$PHANTOMBOT_OWNER" \
      -e "PHANTOMBOT_PANELPASSWORD=$PHANTOMBOT_PANELPASSWORD" \
      -e "PHANTOMBOT_PANELUSER=$PHANTOMBOT_PANELUSER" \
      -e "PHANTOMBOT_USER=$PHANTOMBOT_USER" \
      --name "$DOCKER_CONTAINER_NAME" \
      -p "25000-25005:25000-25005" \
      -it "$DOCKER_NAME:$DOCKER_TAG"
    ;;
  stop)
    docker stop "$DOCKER_CONTAINER_NAME"
    ;;
  push)
    docker push "$DOCKER_REPO:$DOCKER_TAG"
    ;;
  *)
    echo "Usage: $0 {build|run|stop}"
    exit 1
esac